#LOCALREPO=$(shell pwd)/hostdir/binpkgs/
#${HOME}/prg/xbps-packages/
#XBPS_PACKAGES=${HOME}/prg/xbps-packages

all:
	#linux32 ./xbps-src -a i686 -r $(LOCALREPO) -j10 pkg radare2-git
	linux32 ./xbps-src -a i686 -j10 pkg radare2-git
